### PR TITLE
Adds Corporate Fraud Case Study Video

### LINKED ISSUE #42: Video on financial fraud case
As an investigator or regular user, I want to watch a video on how SeeShells could be used in a financial fraud case.

### PR DESCRIPTION
**Pull request by klaki892**
Github cannot view large files / videos natively. 
To review the video, you'll have to download the raw file. (Just select `View Raw` on the side of the file in the changed files view.

Resolves #42

### CODE REVIEW

**Comment by klaki892** [comment]
Because this is a large binary file being added to the repo, it does increase the fetch and clone time for the entire repo from this point forward.  Using [Git LFS](https://git-lfs.github.com/) is an avenue that Github recommends to support such large files. But because it's an add-on for GitHub I wanted to receive team input for if we want to bother with this storage optimization route.

**Comment by szczura** [comment]
Can we just have Leinecker upload it to his youtube channel and put a link to it in the readme?

**Comment by bridCquinn** [comment]
Same question as Sara.

**Comment by klaki892** [comment]
> Can we just have Leinecker upload it to his youtube channel and put a link to it in the readme?

I assume eventually this will be the case. 
If we don't want a copy of the video in the repository we don't have to merge this PR, but this is still a way to review the content of the video and have it redone if needed before delivering it to Leinecker.

**Comment by klaki892** [comment]
Before merging i want to confirm everyone is fine with this being merged.
(:+1: reactions)

**Pull request merged**
